# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Prod

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
-task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(1)(6680b99f-2830-42c6-b696-95b4db1ceeca)'
    subscriptionId: '6680b99f-2830-42c6-b696-95b4db1ceeca'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Adls_sagarR2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'adf-project1-SS/ARMTemplateForFactory.json'
    csmParametersFile: 'adf-project1-SS/ARMTemplateParametersForFactory.json'
    deploymentMode: 'Complete'